DAWSlack/Controllers/CategoriesController.cs
using DAWSlack.Data;
using DAWSlack.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace DAWSlack.Controllers
{
    public class CategoriesController : Controller
    {
        private readonly ApplicationDbContext db;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly RoleManager<IdentityRole> _roleManager;
        public CategoriesController(
        ApplicationDbContext context,
        UserManager<ApplicationUser> userManager,
        RoleManager<IdentityRole> roleManager
        )
        {
            db = context;
            _userManager = userManager;
            _roleManager = roleManager;
        }
        public ActionResult Index()
        {
            var categories = from category in db.Categories
                             orderby category.CategoryName
                             select category;
            ViewBag.Categories = categories;
            return View();
        }

        public ActionResult Show(int id)
        {
            Category category = db.Categories.Find(id);
            ViewBag.Category = category;
            return View();
        }

        public ActionResult New()
        {
            return View();
        }

        [HttpPost]
        public ActionResult New(Category cat)
        {
            try
            {
                db.Categories.Add(cat);
                db.SaveChanges();
                TempData["message"] = "Categoria a fost adaugata";
                return RedirectToAction("Index");
            }
            catch (Exception e)
            {
                return View(cat);
            }
        }

        public ActionResult Edit(int id)
        {
            Category category = db.Categories.Find(id);
            ViewBag.Category = category;
            return View();
        }

        [HttpPost]
        public ActionResult Edit(int id, Category requestCategory)
        {
            if (!ModelState.IsValid)
            {
                return View(requestCategory); 
            }

            try
            {
                Category category = db.Categories.Find(id);
                if (category == null)
                {
                    return NotFound(); 
                }
                category.CategoryName = requestCategory.CategoryName;
                category.CategoryDescription = requestCategory.CategoryDescription;

                db.SaveChanges();

                TempData["message"] = "Categoria a fost modificată cu succes.";
                return RedirectToAction("Index");
            }
            catch (Exception)
            {
                TempData["error"] = "A apărut o eroare. Te rugăm să încerci din nou.";
                return View(requestCategory);
            }
        }



        [HttpPost]
        public ActionResult Delete(int id)
        {
            Category category = db.Categories.Find(id);
            db.Categories.Remove(category);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

DAWSlack/Controllers/ChatChannelsController.cs
using DAWSlack.Data;
using DAWSlack.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System.Text.RegularExpressions;
using System.Threading.Channels;


namespace DAWSlack.Controllers
{
    public class ChatChannelsController : Controller
    {
        private readonly ApplicationDbContext db;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly RoleManager<IdentityRole> _roleManager;
        public ChatChannelsController(
        ApplicationDbContext context,
        UserManager<ApplicationUser> userManager,
        RoleManager<IdentityRole> roleManager
        )
        {
            db = context;
            _userManager = userManager;
            _roleManager = roleManager;
        }

        //public ActionResult Index()
        //{
        //    var channels = from channel in db.Channels
        //                   orderby channel.ChannelName
        //                   select channel;
        //    ViewBag.Channels = channels;
        //    return View();
        //}

        //public ActionResult Show(int id)
        //{
        //    ChatChannel channel = db.Channels.Find(id);
        //    ViewBag.Channels = channel;
        //    return View();
        //}



        [NonAction]
        public IEnumerable<SelectListItem> GetAllCategories()
        {
            // generam o lista de tipul SelectListItem fara elemente
            var selectList = new List<SelectListItem>();

            // extragem toate categoriile din baza de date
            var categories = from cat in db.Categories
                             select cat;

            // iteram prin categorii
            foreach (var category in categories)
            {
                // adaugam in lista elementele necesare pentru dropdown
                // id-ul categoriei si denumirea acesteia
                selectList.Add(new SelectListItem
                {
                    Value = category.Id.ToString(),
                    Text = category.CategoryName
                });
            }
            /* Sau se poate implementa astfel: 
             * 
            foreach (var category in categories)
            {
                var listItem = new SelectListItem();
                listItem.Value = category.Id.ToString();
                listItem.Text = category.CategoryName;

                selectList.Add(listItem);
             }*/


            // returnam lista de categorii
            return selectList;
        }

        [Authorize(Roles = "User,Moderator,Admin")]
        public ActionResult New()
        {
            ChatChannel channel = new ChatChannel();

            channel.Categ = GetAllCategories();

            return View(channel);
        }

        [HttpPost]
        [Authorize(Roles = "User,Moderator,Admin")]
        public IActionResult New(ChatChannel channel)
        {
            if (ModelState.IsValid)
            {
                channel.UserId= _userManager.GetUserId(User);
                db.Channels.Add(channel);
                db.SaveChanges();
                TempData["message"] = "Canalul a fost creat";
                TempData["messageType"] = "alert-success";
                int idChannel = channel.Id;
                string idUser = channel.UserId;

                
                UserChannel userChannel = new UserChannel();
                userChannel.ChannelId = idChannel;
                userChannel.UserId = idUser;
                if (User.IsInRole("Admin"))
                {
                    userChannel.Roles = "Admin";
                }
                else
                {
                    userChannel.Roles = "Moderator";
                    UserChannel addAdmin = new UserChannel();
                    addAdmin.ChannelId = idChannel;
                    addAdmin.Roles = "Admin";

                    var roleId = db.Roles.Where(r => r.Name == "Admin").Select(r => r.Id).FirstOrDefault();

                    var adminUserId = db.UserRoles
                        .Where(ur => ur.RoleId == roleId)
                        .Select(uc => uc.UserId)
                        .FirstOrDefault();
                    addAdmin.UserId = adminUserId;
                    db.UserChannels.Add(addAdmin);
                    db.SaveChanges();
                }
                db.UserChannels.Add(userChannel);
                db.SaveChanges();
                return RedirectToAction("Index");
                //return View();
            }
            else
            {
                channel.Categ = GetAllCategories();
                return View(channel);
            }
        }

        //public ActionResult New(ChatChannel channel)
        //{
        //    try
        //    {
        //        db.Channels.Add(channel);
        //        db.SaveChanges();
        //        TempData["message"] = "Canalul a fost adaugata";
        //        return RedirectToAction("Index");
        //    }
        //    catch (Exception e)
        //    {
        //        return View(channel);
        //    }
        //}

        [Authorize(Roles = "User,Moderator,Admin")]
        public IActionResult Index()
        {
            var channels = db.Channels.OrderByDescending(a => a.ChannelName);

            // ViewBag.OriceDenumireSugestiva
            // ViewBag.Articles = articles;

            if (TempData.ContainsKey("message"))
            {
                ViewBag.Message = TempData["message"];
                ViewBag.Alert = TempData["messageType"];
            }

            // MOTOR DE CAUTARE

            var search = "";

            if (Convert.ToString(HttpContext.Request.Query["search"]) != null)
            {
                search = Convert.ToString(HttpContext.Request.Query["search"]).Trim(); // eliminam spatiile libere 

                // Cautare in articol (Title si Content)

                List<int> channelsIds = db.Channels.Where
                                        (
                                         at => at.ChannelName.Contains(search)
                                        ).Select(a => a.Id).ToList();




                // Lista articolelor care contin cuvantul cautat
                // fie in articol -> Title si Content
                // fie in comentarii -> Content
                //articles = db.Channels.Where(article => mergedIds.Contains(article.Id))

                channels = db.Channels.Where(channels => channelsIds.Contains(channels.Id))
                    .OrderByDescending(a => a.ChannelName);

            }

            ViewBag.SearchString = search;

            // AFISARE PAGINATA

            // Alegem sa afisam 3 articole pe pagina
            int _perPage = 3;

            // Fiind un numar variabil de articole, verificam de fiecare data utilizand 
            // metoda Count()

            int totalItems = channels.Count();

            // Se preia pagina curenta din View-ul asociat
            // Numarul paginii este valoarea parametrului page din ruta
            // /Articles/Index?page=valoare

            var currentPage = Convert.ToInt32(HttpContext.Request.Query["page"]);

            // Pentru prima pagina offsetul o sa fie zero
            // Pentru pagina 2 o sa fie 3 
            // Asadar offsetul este egal cu numarul de articole care au fost deja afisate pe paginile anterioare
            var offset = 0;

            // Se calculeaza offsetul in functie de numarul paginii la care suntem
            if (!currentPage.Equals(0))
            {
                offset = (currentPage - 1) * _perPage;
            }

            // Se preiau articolele corespunzatoare pentru fiecare pagina la care ne aflam 
            // in functie de offset
            var paginatedArticles = channels.Skip(offset).Take(_perPage);


            // Preluam numarul ultimei pagini
            ViewBag.lastPage = Math.Ceiling((float)totalItems / (float)_perPage);

            // Trimitem articolele cu ajutorul unui ViewBag catre View-ul corespunzator
            ViewBag.Channels = paginatedArticles;

            // DACA AVEM AFISAREA PAGINATA IMPREUNA CU SEARCH

            if (search != "")
            {
                ViewBag.PaginationBaseUrl = "/ChatChannels/Index/?search=" + search + "&page";
            }
            else
            {
                ViewBag.PaginationBaseUrl = "/ChatChannels/Index/?page";
            }

            return View();
        }
        [Authorize(Roles = "User,Moderator,Admin")]
        public IActionResult MyChannels()
        {
            // Obține UserId-ul utilizatorului curent
            var userId = _userManager.GetUserId(User);

            // Selectează doar canalele unde utilizatorul este "Creator" sau "Moderator"
            var channels = db.UserChannels
                .Where(uc => uc.UserId == userId && (uc.Roles == "Creator" || uc.Roles == "Moderator" || uc.Roles == "Admin"))
                .Select(uc => uc.ChannelId) // Selectăm doar ID-urile canalelor
                .ToList();

            // Preluăm datele canalelor asociate acestor ID-uri
            var myChannels = db.Channels
                .Where(ch => channels.Contains(ch.Id))
                .OrderBy(ch => ch.ChannelName)
                .ToList();

            // Transmitem canalele către View
            ViewBag.MyChannels = myChannels;

            return View();
        }

        [Authorize(Roles = "User,Moderator,Admin")]
        public IActionResult EditChannel(int id)
        {
            // Găsește canalul după ID
            var channel = db.Channels.FirstOrDefault(c => c.Id == id);
            if (channel == null)
            {
                return NotFound();
            }

            // JOIN între UserChannels și AspNetUsers
            var participants = (from uc in db.UserChannels
                                join user in db.Users

DAWSlack/Controllers/UsersController.cs
using DAWSlack.Data;
using DAWSlack.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace DAWSlack.Controllers
{
    [Authorize(Roles = "Admin")]
    public class UsersController : Controller
    {
        private readonly ApplicationDbContext db;

        private readonly UserManager<ApplicationUser> _userManager;

        private readonly RoleManager<IdentityRole> _roleManager;

        public UsersController(
            ApplicationDbContext context,
            UserManager<ApplicationUser> userManager,
            RoleManager<IdentityRole> roleManager
            )
        {
            db = context;

            _userManager = userManager;

            _roleManager = roleManager;
        }
        public IActionResult Index()
        {
            var users = from user in db.Users
                        orderby user.UserName
                        select user;

            ViewBag.UsersList = users;

            return View();
        }

        public async Task<ActionResult> Show(string id)
        {
            ApplicationUser user = db.Users.Find(id);
            var roles = await _userManager.GetRolesAsync(user);    

            ViewBag.Roles = roles;

            ViewBag.UserCurent = await _userManager.GetUserAsync(User);

            return View(user);
        }

        public async Task<ActionResult> Edit(string id)
        {
            ApplicationUser user = db.Users.Find(id);


            var roleNames = await _userManager.GetRolesAsync(user); // Lista de nume de roluri

            // Cautam ID-ul rolului in baza de date
            ViewBag.UserRole = _roleManager.Roles
                                              .Where(r => roleNames.Contains(r.Name))
                                              .Select(r => r.Id)
                                              .First(); // Selectam 1 singur rol

            return View(user);
        }

 
    }
}

DAWSlack/Views/Shared/Channellnfo.cshtml
@model DAWSlack.Models.ChatChannel


<div class="card-body" id="infoChannel">
    @if (Model != null)
    {
        <h3 class="card-title alert-success py-3 px-3 rounded-2">
            @(Model.ChannelName)
        </h3>

        <div class="card-text">
            @Html.Raw(Model.ChannelDescription ?? "No Description Available")
        </div>

        <div class="d-flex justify-content-between flex-row mt-5">
            <div>
                <i class="bi bi-globe"></i>
                @(Model.Category?.CategoryName ?? "No Category")
            </div>
            <div>
                <i class="bi bi-person"></i>
                @(Model.User?.UserName ?? "No User")
            </div>
        </div>
    }
    else
    {
        <div class="alert alert-danger">
            Channel information is missing.
        </div>
    }
</div>

@*
<div class="container" id="contentAfisare">

    @foreach (var message in ViewBag.Messages)
    {
        <p>@message.UserId</p>
        <p>@message.Content</p>
    }

</div>

*@
<div class="container" id="contentAfisare">
    @if (ViewBag.MessagesWithUsers != null)
    {
        <div id="messageBox">
            @foreach (var message in ViewBag.MessagesWithUsers)
            {
                <div class="message">
                    <div class="user-info">
                        <span class="username">@message.UserName</span>
                        <span class="userid">(@message.UserId)</span>
                    </div>
                    <div class="message-content">
                        @Html.Raw(message.Content) <!-- Render HTML content with embedded media -->
                    </div>
                </div>
            }
        </div>

    }
    else
    {
        <p>No messages available.</p>
    }
</div>


@* Afisarea formularului in care se poate adauga un comentariu *@

@*
@foreach (var comm in Model.Messages)
{
    <div class="container">
        <div class="row">
            <div class="col-md-2"></div>

            <div class="col-md-8">

                <div>

                    <p>@comm.Content</p>
                    <small>@comm.Date</small>
                    <strong><i class="bi bi-person"> @comm.User.UserName</i></strong>

                </div>
                <br>

                @if (comm.UserId == ViewBag.UserCurent || ViewBag.EsteAdmin == true)
                {
                    <div class="d-flex">
                        <div>
                            <a class="btn btn-outline-primary" asp-controller="Comments" asp-action="Edit" asp-route-id="@comm.Id">
                                <i class="bi bi-pencil-square"></i> Editeaza
                            </a>

                        </div>
                        <div>
                            <form method="post" asp-controller="Comments" asp-action="Delete" asp-route-id="@comm.Id">

                                <button class="btn btn-outline-danger" type="submit"><i class="bi bi-trash"></i>Sterge</button>

                            </form>
                        </div>
                    </div>
                }

                <br />
            </div>

            <div class="col-md-2"></div>

        </div>

    </div>
}
*@

@*
<div class="container" id="writeMessage">
    <div class="row">

        <div class="col-md-2"></div>

        <div class="col-md-8">

            <div class="card">

                <form method="post" asp-controller="ChatChannels" asp-action="Show">

                    <div class="card-body">

                        <input type="hidden" name="ChannelId" value="@Model.Id" />

                        <label>Continut Mesaj</label>
                        <br />

                        <textarea class="form-control" name="Content"></textarea>

                        <span asp-validation-for="ChannelDescription" class="text-danger"></span>
                        <br /><br />

                        <button class="btn btn-success" type="submit">Adauga Mesaj</button>

                    </div>

                </form>

            </div>

        </div>

        <div class="col-md-2"></div>

    </div>
</div>
*@

<div class="container" id="writeMessage">
    <div class="row">
        <div class="col-md-2"></div>
        <div class="col-md-8">
            <div class="card">
                <form method="post" asp-controller="ChatChannels" asp-action="Show">
                    <div class="card-body">
                        <input type="hidden" name="ChannelId" value="@Model.Id" />

                        <label>Continut Mesaj</label>
                        <br />
                        <textarea class="form-control" name="Content" placeholder="Paste your image/video URL here"></textarea>
                        <br /><br />

                        <button class="btn btn-success" type="submit">Adauga Mesaj</button>
                    </div>
                </form>
            </div>
        </div>
        <div class="col-md-2"></div>
    </div>
</div>

DAWSlack/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - DAWSlack</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    <link rel="stylesheet" href="~/DAWSlack.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                @*<a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
                    <div class="logo-container">
                        <img id="logo" src="~/Logo.png" alt="logo">
                    </div>
                </a>*@
                <div class="logo-container">
                    <img id="logo" src="~/Logo.png" alt="logo">
                </div>
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Virtual.Cete</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        @if (User.IsInRole("Admin"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Categories" asp-action="Index">Afiseaza categoriile</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Categories" asp-action="New">Creeaza o categorie</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Users" asp-action="Index">Afiseaza utilizatorii</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="ChatChannels" asp-action="Index">Afiseaza canalele</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="ChatChannels" asp-action="MyChannels">Canalele mele</a>
                            </li>
                        }

                        @if (User.IsInRole("Moderator"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Users" asp-action="Index">Afiseaza utilizatorii</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="ChatChannels" asp-action="Index">Afiseaza canalele</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="ChatChannels" asp-action="MyChannels">Canalele mele</a>
                            </li>
                        }

                        @if (User.IsInRole("User"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="ChatChannels" asp-action="Index">Afiseaza canalele</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="ChatChannels" asp-action="New">Creeaza un canal</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="ChatChannels" asp-action="MyChannels">Canalele mele</a>
                            </li>
                        }
                        
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - DAWSlack - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>