DAWSlack/Models/ChatChannel.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DAWSlack.Models
{
    public class ChatChannel
    {
        [Key]
        public int Id { get; set; }

        [Required(ErrorMessage = "Denumirea canalului este necesară.")]
        [MaxLength(100, ErrorMessage = "Denumirea nu poate depăși 100 de caractere.")]
        public string ChannelName { get; set; }
        [Required(ErrorMessage = "Descrierea canalului este necesară.")]
        [MaxLength(1000, ErrorMessage = "Descrierea nu poate depăși 1000 de caractere")]
        public string? ChannelDescription { get; set; }
        public string? UserId { get; set; }
        public virtual ApplicationUser? User { get; set; }
        public virtual Category? Category { get; set; }
        // cheie externa (FK) - un canal are asociata una sau mai multe categorii
        public int? CategoryId { get; set; }
        public virtual ICollection<ChannelRole>? ChannelRoles { get; set; }
        public virtual ICollection<UserChannel>? UserChannels { get; set; }
        public virtual ICollection<Message>? Messages { get; set; }
        public virtual ICollection<ApplicationUser>? Users { get; set; }
        public virtual ICollection<ApplicationUser>? Mods { get; set; }

        [NotMapped]
        public IEnumerable<SelectListItem>? Categ { get; set; }
    }
}

DAWSlack/Controllers/ChatChannelsController.cs
using DAWSlack.Data;
using DAWSlack.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System.Text.RegularExpressions;
using System.Threading.Channels;


namespace DAWSlack.Controllers
{
    public class ChatChannelsController : Controller
    {
        private readonly ApplicationDbContext db;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly RoleManager<IdentityRole> _roleManager;
        public ChatChannelsController(
        ApplicationDbContext context,
        UserManager<ApplicationUser> userManager,
        RoleManager<IdentityRole> roleManager
        )
        {
            db = context;
            _userManager = userManager;
            _roleManager = roleManager;
        }

        //public ActionResult Index()
        //{
        //    var channels = from channel in db.Channels
        //                   orderby channel.ChannelName
        //                   select channel;
        //    ViewBag.Channels = channels;
        //    return View();
        //}

        //public ActionResult Show(int id)
        //{
        //    ChatChannel channel = db.Channels.Find(id);
        //    ViewBag.Channels = channel;
        //    return View();
        //}



        [NonAction]
        public IEnumerable<SelectListItem> GetAllCategories()
        {
            // generam o lista de tipul SelectListItem fara elemente
            var selectList = new List<SelectListItem>();

            // extragem toate categoriile din baza de date
            var categories = from cat in db.Categories
                             select cat;

            // iteram prin categorii
            foreach (var category in categories)
            {
                // adaugam in lista elementele necesare pentru dropdown
                // id-ul categoriei si denumirea acesteia
                selectList.Add(new SelectListItem
                {
                    Value = category.Id.ToString(),
                    Text = category.CategoryName
                });
            }
            /* Sau se poate implementa astfel: 
             * 
            foreach (var category in categories)
            {
                var listItem = new SelectListItem();
                listItem.Value = category.Id.ToString();
                listItem.Text = category.CategoryName;

                selectList.Add(listItem);
             }*/


            // returnam lista de categorii
            return selectList;
        }

        [Authorize(Roles = "User,Moderator,Admin")]
        public ActionResult New()
        {
            ChatChannel channel = new ChatChannel();

            channel.Categ = GetAllCategories();

            return View(channel);
        }

        [HttpPost]
        [Authorize(Roles = "User,Moderator,Admin")]
        public IActionResult New(ChatChannel channel)
        {
            if (ModelState.IsValid)
            {
                channel.UserId= _userManager.GetUserId(User);
                db.Channels.Add(channel);
                db.SaveChanges();
                TempData["message"] = "Canalul a fost creat";
                TempData["messageType"] = "alert-success";
                int idChannel = channel.Id;
                string idUser = channel.UserId;

                
                UserChannel userChannel = new UserChannel();
                userChannel.ChannelId = idChannel;
                userChannel.UserId = idUser;
                if (User.IsInRole("Admin"))
                {
                    userChannel.Roles = "Admin";
                }
                else
                {
                    userChannel.Roles = "Moderator";
                    UserChannel addAdmin = new UserChannel();
                    addAdmin.ChannelId = idChannel;
                    addAdmin.Roles = "Admin";

                    var roleId = db.Roles.Where(r => r.Name == "Admin").Select(r => r.Id).FirstOrDefault();

                    var adminUserId = db.UserRoles
                        .Where(ur => ur.RoleId == roleId)
                        .Select(uc => uc.UserId)
                        .FirstOrDefault();
                    addAdmin.UserId = adminUserId;
                    db.UserChannels.Add(addAdmin);
                    db.SaveChanges();
                }
                db.UserChannels.Add(userChannel);
                db.SaveChanges();
                return RedirectToAction("Index");
                //return View();
            }
            else
            {
                channel.Categ = GetAllCategories();
                return View(channel);
            }
        }

        //public ActionResult New(ChatChannel channel)
        //{
        //    try
        //    {
        //        db.Channels.Add(channel);
        //        db.SaveChanges();
        //        TempData["message"] = "Canalul a fost adaugata";
        //        return RedirectToAction("Index");
        //    }
        //    catch (Exception e)
        //    {
        //        return View(channel);
        //    }
        //}

        [Authorize(Roles = "User,Moderator,Admin")]
        public IActionResult Index()
        {
            var channels = db.Channels.OrderByDescending(a => a.ChannelName);

            // ViewBag.OriceDenumireSugestiva
            // ViewBag.Articles = articles;

            if (TempData.ContainsKey("message"))
            {
                ViewBag.Message = TempData["message"];
                ViewBag.Alert = TempData["messageType"];
            }

            // MOTOR DE CAUTARE

            var search = "";

            if (Convert.ToString(HttpContext.Request.Query["search"]) != null)
            {
                search = Convert.ToString(HttpContext.Request.Query["search"]).Trim(); // eliminam spatiile libere 

                // Cautare in articol (Title si Content)

                List<int> channelsIds = db.Channels.Where
                                        (
                                         at => at.ChannelName.Contains(search)
                                        ).Select(a => a.Id).ToList();




                // Lista articolelor care contin cuvantul cautat
                // fie in articol -> Title si Content
                // fie in comentarii -> Content
                //articles = db.Channels.Where(article => mergedIds.Contains(article.Id))

                channels = db.Channels.Where(channels => channelsIds.Contains(channels.Id))
                    .OrderByDescending(a => a.ChannelName);

            }

            ViewBag.SearchString = search;

            // AFISARE PAGINATA

            // Alegem sa afisam 3 articole pe pagina
            int _perPage = 3;

            // Fiind un numar variabil de articole, verificam de fiecare data utilizand 
            // metoda Count()

            int totalItems = channels.Count();

            // Se preia pagina curenta din View-ul asociat
            // Numarul paginii este valoarea parametrului page din ruta
            // /Articles/Index?page=valoare

            var currentPage = Convert.ToInt32(HttpContext.Request.Query["page"]);

            // Pentru prima pagina offsetul o sa fie zero
            // Pentru pagina 2 o sa fie 3 
            // Asadar offsetul este egal cu numarul de articole care au fost deja afisate pe paginile anterioare
            var offset = 0;

            // Se calculeaza offsetul in functie de numarul paginii la care suntem
            if (!currentPage.Equals(0))
            {
                offset = (currentPage - 1) * _perPage;
            }

            // Se preiau articolele corespunzatoare pentru fiecare pagina la care ne aflam 
            // in functie de offset
            var paginatedArticles = channels.Skip(offset).Take(_perPage);


            // Preluam numarul ultimei pagini
            ViewBag.lastPage = Math.Ceiling((float)totalItems / (float)_perPage);

            // Trimitem articolele cu ajutorul unui ViewBag catre View-ul corespunzator
            ViewBag.Channels = paginatedArticles;

            // DACA AVEM AFISAREA PAGINATA IMPREUNA CU SEARCH

            if (search != "")
            {
                ViewBag.PaginationBaseUrl = "/ChatChannels/Index/?search=" + search + "&page";
            }
            else
            {
                ViewBag.PaginationBaseUrl = "/ChatChannels/Index/?page";
            }

            return View();
        }
        [Authorize(Roles = "User,Moderator,Admin")]
        public IActionResult MyChannels()
        {
            // Obține UserId-ul utilizatorului curent
            var userId = _userManager.GetUserId(User);

            // Selectează doar canalele unde utilizatorul este "Creator" sau "Moderator"
            var channels = db.UserChannels
                .Where(uc => uc.UserId == userId && (uc.Roles == "Creator" || uc.Roles == "Moderator" || uc.Roles == "Admin"))
                .Select(uc => uc.ChannelId) // Selectăm doar ID-urile canalelor
                .ToList();

            // Preluăm datele canalelor asociate acestor ID-uri
            var myChannels = db.Channels
                .Where(ch => channels.Contains(ch.Id))
                .OrderBy(ch => ch.ChannelName)
                .ToList();

            // Transmitem canalele către View
            ViewBag.MyChannels = myChannels;

            return View();
        }

        [Authorize(Roles = "User,Moderator,Admin")]
        public IActionResult EditChannel(int id)
        {
            // Găsește canalul după ID
            var channel = db.Channels.FirstOrDefault(c => c.Id == id);
            if (channel == null)
            {
                return NotFound();
            }

            // JOIN între UserChannels și AspNetUsers
            var participants = (from uc in db.UserChannels
                                join user in db.Users

DAWSlack/Controllers/MessagesController.cs
using DAWSlack.Data;
using DAWSlack.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace DAWSlack.Controllers
{
    public class MessagesController : Controller
    {
        private readonly ApplicationDbContext db;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly RoleManager<IdentityRole> _roleManager;
        public MessagesController(
        ApplicationDbContext context,
        UserManager<ApplicationUser> userManager,
        RoleManager<IdentityRole> roleManager
        )
        {
            db = context;
            _userManager = userManager;
            _roleManager = roleManager;
        }

        [HttpPost]
            public IActionResult New(Message mes)
            {
                mes.Date = DateTime.Now;

                try
                {
                    db.Messages.Add(mes);
                    db.SaveChanges();
                    return Redirect("/Messages/Show/" + mes.ChannelId);
                }

                catch (Exception)
                {
                    return Redirect("/Messages/Show/" + mes.ChannelId);
                }

            }

        //// Stergerea unui comentariu asociat unui articol din baza de date
        //[HttpPost]
        //public IActionResult Delete(int id)
        //{
        //    Message message = db.Messages.Find(id);
        //    if (message == null)
        //    {
        //        TempData["message"] = "Message not found.";
        //        TempData["messageType"] = "alert-danger";
        //        return RedirectToAction("Show", "ChatChannels"); // Redirect back to the channel
        //    }

        //    db.Messages.Remove(message);
        //    db.SaveChanges();

        //    TempData["message"] = "Message deleted successfully.";
        //    TempData["messageType"] = "alert-success";
        //    return RedirectToAction("Show", "ChatChannels"); // Redirect back to the channel
        //}

            [HttpPost]
            public IActionResult Delete(int id)
            {
                var message = db.Messages.FirstOrDefault(m => m.Id == id);

                if (message == null)
                {
                    TempData["message"] = "Message not found.";
                    TempData["messageType"] = "alert-danger";
                    return RedirectToAction("Show", "ChatChannels");
                }

                db.Messages.Remove(message);
                db.SaveChanges();

                TempData["message"] = "Message deleted successfully.";
                TempData["messageType"] = "alert-success";
                return RedirectToAction("Show", "ChatChannels", new { id = message.ChannelId });
            }

        [Authorize(Roles = "User,Editor,Admin")]
        public IActionResult Edit(int id)
        {
            Message comm = db.Messages.Find(id);

            if (comm.UserId == _userManager.GetUserId(User) || User.IsInRole("Admin"))
            {
                return View(comm);
            }
            else
            {
                TempData["message"] = "Nu aveti dreptul sa editati comentariul";
                TempData["messageType"] = "alert-danger";
                return RedirectToAction("Index", "Articles");
            }
        }

        [HttpPost]
        [Authorize(Roles = "User,Editor,Admin")]
        public IActionResult Edit(int id, Message requestComment)
        {
            Message comm = db.Messages.Find(id);

            if (comm.UserId == _userManager.GetUserId(User) || User.IsInRole("Admin"))
            {
                if (ModelState.IsValid)
                {
                    comm.Content = requestComment.Content;

                    db.SaveChanges();

                    return Redirect("/ChatChannels/Show/" + comm.ChannelId);
                }
                else
                {
                    return View(requestComment);
                }
            }
            else
            {
                TempData["message"] = "Nu aveti dreptul sa editati comentariul";
                TempData["messageType"] = "alert-danger";
                return RedirectToAction("Show", "ChatChannels", new { id = requestComment.ChannelId });
            }
        }
    }
    }

DAWSlack/Views/ChatChannels/EditChannel.cshtml
@model DAWSlack.Models.ChatChannel

@{
    ViewBag.Title = "Editare Canal";
}

<h2>Editare Canal</h2>

<form asp-action="EditChannel" method="post">
    <input type="hidden" asp-for="Id" />

    <div class="form-group">
        <label asp-for="ChannelName"></label>
        <input type="text" asp-for="ChannelName" class="form-control" />
        <span asp-validation-for="ChannelName" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="ChannelDescription"></label>
        <textarea asp-for="ChannelDescription" class="form-control"></textarea>
        <span asp-validation-for="ChannelDescription" class="text-danger"></span>
    </div>

    <button type="submit" class="btn btn-primary">Salvează modificările</button>
    <a href="@Url.Action("Index", "ChatChannels")" class="btn btn-secondary">Renunță</a>
</form>

<h3>Participanți</h3>

@if (ViewBag.Participants != null && ViewBag.Participants.Count > 0)
{
    <table class="table table-striped">
        <thead>
            <tr>
                <th>Nume Utilizator</th>
                <th>Rol</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var participant in ViewBag.Participants)
            {
                <tr>
                    <td>@participant.UserName</td>
                    <td>@participant.Role</td>
                </tr>
                <td>
                    @if (participant.Role == "Member")
                    {
                        <!-- Button Add Roles -->
                        <form asp-action="AddRole" method="post" style="display: inline-block;">
                            <input type="hidden" name="ChannelId" value="@Model.Id" />
                            <input type="hidden" name="UserId" value="@participant.UserId" />
                            <button type="submit" class="btn btn-success">Add Moderator</button>
                        </form>
                    }
                    else if (participant.Role == "Moderator")
                    {
                        <!-- Button Revoke Role -->
                        <form asp-action="RevokeRole" method="post" style="display: inline-block;">
                            <input type="hidden" name="ChannelId" value="@Model.Id" />
                            <input type="hidden" name="UserId" value="@participant.UserId" />
                                        <button type="submit" class="btn btn-success">Delete Moderator</button>
                        </form>
                    }
                    else if (participant.Role == "Admin")
                    {
                        <!-- Admin role, no action allowed -->
                        <span class="badge bg-primary">Admin</span>
                    }
                </td>
                <td>
                    <!-- Remove Participant Button -->
                    @if (participant.UserId != ViewBag.UserCurent && participant.Role == "Member")
                    {
                        <form asp-action="RemoveParticipant" method="post" style="display: inline-block;">
                            <input type="hidden" name="ChannelId" value="@Model.Id" />
                            <input type="hidden" name="UserId" value="@participant.UserId" />
                            <button type="submit" class="btn btn-danger">Remove</button>
                        </form>
                    }
                </td>

            }

        </tbody>
    </table>
}
else
{
    <p>Nu există participanți pentru acest canal.</p>
}
<h3>Cererile de Aderare</h3>
@if (ViewBag.JoinRequests != null && ViewBag.JoinRequests.Count > 0)
{
    <table class="table table-striped">
        <thead>
            <tr>
                <th>Nume Utilizator</th>
                <th>Acțiuni</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var request in ViewBag.JoinRequests)
            {
                <tr>
                    <td>@request.UserName</td>
                    <td>
                        <!-- Accept Button -->
                        <form asp-action="AcceptJoinRequest" method="post" style="display: inline-block;">
                            <input type="hidden" name="RequestId" value="@request.RequestId" />
                            <button type="submit" class="btn btn-success">Acceptă</button>
                        </form>

                        <!-- Reject Button -->
                        <form asp-action="RejectJoinRequest" method="post" style="display: inline-block;">
                            <input type="hidden" name="RequestId" value="@request.RequestId" />
                            <button type="submit" class="btn btn-danger">Respinge</button>
                        </form>
                    </td>
                </tr>
            }
        </tbody>

    </table>
}
else
{
    <p>Nu există cereri de aderare pentru acest canal.</p>
}

DAWSlack/Views/ChatChannels/MyChannels.cshtml
@{
    ViewBag.Title = "Canalele mele";
    var myChannels = ViewBag.MyChannels as List<DAWSlack.Models.ChatChannel>; // Asigură-te că namespace-ul este corect
}

<h2>Canalele mele</h2>

@if (myChannels != null && myChannels.Count > 0)
{
    <ul>
        @foreach (var channel in myChannels)
        {
            <li style="margin-bottom: 15px;">
                <h4>@channel.ChannelName</h4>
                <p>@channel.ChannelDescription</p>
                <div>
                    <!-- Button Edit -->
                    <a href="@Url.Action("EditChannel", "ChatChannels", new { id = channel.Id })" class="btn btn-warning">
                        Edit
                    </a>

                    <!-- Button Delete -->
                    <form asp-action="DeleteChannel" method="post" style="display: inline-block;"
                          onsubmit="return confirm('Sigur doriți să ștergeți acest canal?');">
                        <input type="hidden" name="id" value="@channel.Id" />
                        <button type="submit" class="btn btn-danger">Delete</button>
                    </form>
                </div>
            </li>
        }
    </ul>
}
else
{
    <p>Nu aveți canale la care sunteți "Creator" sau "Moderator".</p>
}

DAWSlack/Views/ChatChannels/Show.cshtml
@if (TempData["message"] != null)
{
    <div class="alert alert-danger">
        @TempData["message"]
    </div>
}
<div class="discord-style">
    <!-- Sidebar -->
    <div class="sidebar">
        <h3>@ViewBag.Title</h3>
        <div class="search-bar">
            <form method="GET">
                <input type="text" placeholder="Search topics or keywords" name="search" value="@ViewBag.SearchString">
                <button type="submit">Search</button>
            </form>
        </div>

        @foreach (var channel in ViewBag.Channels)
        {
            <div class="channel-item" data-id="@channel.Id">
                <a href="javascript:void(0);">@channel.ChannelName</a>
            </div>
        }

        <div class="pagination-nav">
            <ul class="pagination">
                <li class="page-item">
                    <a class="page-link" href="@ViewBag.PaginationBaseUrl=1" aria-label="Previous">
                        &laquo;
                    </a>
                </li>
                @for (int i = 1; i <= ViewBag.lastPage; i++)
                {
                    <li class="page-item">
                        <a class="page-link" href="@ViewBag.PaginationBaseUrl=@i">@i</a>
                    </li>
                }
                <li class="page-item">
                    <a class="page-link" href="@ViewBag.PaginationBaseUrl=@ViewBag.lastPage" aria-label="Next">
                        &raquo;
                    </a>
                </li>
            </ul>
        </div>

        <a class="btn btn-success" asp-area="" asp-controller="ChatChannels" asp-action="New">Add Channel</a>
    </div>
    
    <!-- Content and Participants -->
    <div class="main-content">
        <!-- Content Section -->
        <div class="content">
            <div class="card-body" id="infoChannel">
                @if (Model != null)
                {
                    <h3 class="card-title alert-success py-3 px-3 rounded-2">
                        @(Model.ChannelName)
                    </h3>

                    <div class="card-text">
                        @Html.Raw(Model.ChannelDescription ?? "No Description Available")
                    </div>

                    <div class="d-flex justify-content-between flex-row mt-5">
                        <div>
                            <i class="bi bi-globe"></i>
                            @(Model.Category?.CategoryName ?? "No Category")
                        </div>
                        <div>
                            <i class="bi bi-person"></i>
                            @(Model.User?.UserName ?? "No User")
                        </div>
                    </div>
                }
                else
                {
                    <div class="alert alert-danger">
                        Channel information is missing.
                    </div>
                }
            </div>

            @if (ViewBag.isParticipant == true)
            {
                <div id="contentAfisare">
                    @if (ViewBag.MessagesWithUsers != null)
                    {
                        @*<div id="messageBox">
                            @foreach (var message in ViewBag.MessagesWithUsers)
                            {
                                <div class="message">
                                    <div class="user-info">
                                        <span class="username">@message.UserName</span>
                                        <span class="userid">(@message.UserId)</span>
                                    </div>
                                    <div class="message-content">
                                        @Html.Raw(message.Content)
                                    </div>
                                </div>
                            }
                        </div>*@


                        <div id="messageBox">
                            @foreach (var message in ViewBag.MessagesWithUsers)
                            {
                                <div class="message">
                                    <!-- User and Message Info -->
                                    <div class="user-info">
                                        <span class="username">@message.UserName </span>
                                        @* <span class="userid">(@message.UserId)</span>*@
                                        <span class="message-date">@message.Date.ToString("g")</span> <!-- Date format -->
                                    </div>
                                    <div class="message-content">
                                        @Html.Raw(message.Content)
                                    </div>

                                    <!-- Action Buttons -->
                                    <div class="message-actions">
                                        @if (ViewBag.UserCurent == message.UserId)
                                        {
                                            <!-- Edit Message -->
                                            <form asp-controller="Messages" asp-action="Edit" method="get" style="display:inline-block;">
                                                <input type="hidden" name="id" value="@message.MessageId" />
                                                <button type="submit" class="btn btn-primary btn-sm">Edit</button>
                                            </form>

                                            <!-- Delete Message -->
                                            <form asp-controller="Messages" asp-action="Delete" method="post" style="display:inline-block;">
                                                <input type="hidden" name="id" value="@message.MessageId" />
                                                <button type="submit" class="btn btn-danger btn-sm">Delete</button>
                                            </form>
                                        }

                                        @if (ViewBag.EsteAdmin || ViewBag.EsteModerator)
                                        {
                                            <!-- Delete Message for Admin/Moderator -->
                                            <form asp-controller="Messages" asp-action="Delete" method="post" style="display:inline-block;">
                                                <input type="hidden" name="id" value="@message.MessageId" />
                                                <button type="submit" class="btn btn-danger btn-sm">Remove</button>
                                            </form>
                                        }
                                    </div>
                                </div>
                            }
                        </div>

                    }
                    else
                    {
                        <p>No messages available.</p>
                    }
                </div>

                <div class="container" id="writeMessage">
                    <div class="card">
                        <form method="post" asp-controller="ChatChannels" asp-action="Show">
                            <div class="card-body">
                                <input type="hidden" name="ChannelId" value="@Model.Id" />
                                <label>Message Content</label>
                                <textarea class="form-control" name="Content" placeholder="Paste your image/video URL here"></textarea>
                                <br />
                                <button class="btn btn-success" type="submit">Add Message</button>
                            </div>
                        </form>
                    </div>
                </div>
            }
            else
            {
                <div class="alert alert-danger">
                    You are not a participant in this channel.
                </div>
                <form asp-action="CreateRequest" method="post">
                    <input type="hidden" name="ChannelId" value="@Model.Id" />
                    <button type="submit" class="btn btn-primary">Request to Join</button>
                </form>
            }
        </div>

        <!-- Participants Section -->
        <div class="participants">
            <h3>Participants</h3>
            @if (ViewBag.Participants != null && ViewBag.Participants.Count > 0)
            {
                <ul class="list-group">
                    @foreach (var participant in ViewBag.Participants)
                    {
                        <li class="list-group-item d-flex justify-content-between align-items-center">
                            <span>@participant.UserName</span>
                            <span class="badge bg-primary">@participant.Role</span>
                        </li>
                    }
                </ul>
            }
            else
            {
                <p>No participants available.</p>
            }
        </div>
    </div>
</div>